---
# Building the image if build_action is local
- name: "Build {{ container_name }}"
  docker_image:
    name: "{{ container_name }}"
    tag: "{{ docker_tag }}"
    state: present
    path: "{{ path }}"
  when: "build_action == 'local'"

# Pulling the image if build_action is pull
- name: "Pull {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    pull: yes
  when: "build_action == 'pull'"
  ignore_errors: yes

# Create command script
- name: Create threat-ingest run script
  template:
    src: "{{ role_path }}/templates/run.j2"
    dest: "{{ role_path }}/files/bin/run.sh"
    mode: 0555

# Building the ingest container
- name: Create Threat Ingest
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    networks:
      - name: "{{ docker_network_name }}"          
    volumes: "{{ volume_list }}"
    published_ports: "{{ '5010:5010' if 'development' in group_names else [] }}"
    env:
      THREAT_INGEST_PORT: 5010
      MONGO_HOST: cti-stix-store-repository
      MONGO_PORT: 27017
      MONGO_DB: stix
      SOCKET_SERVER_HOST: unfetter-socket-server
      SOCKET_SERVER_PORT: 3333
    working_dir: /usr/share/unfetter-threat-ingest
    entrypoint:
      - bin/run.sh
  when: run_action
  ignore_errors: yes
