version: '3.3'
services:
  unfetter-elk:
    image: sebp/elk:630
    container_name: unfetter-elk
    ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"

  unfetter-filebeat:
    image: prima/filebeat:6
    container_name: unfetter-filebeat
    links:
     - unfetter-elk
    depends_on:
     - unfetter-elk
     - unfetter-discover-gateway
    volumes:
     - ./config/elk/filebeat.yml:/filebeat.yml
     - ./config/elk/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
     - log-vol:/var/log

  unfetter-discover-gateway:
    image: nginx:1.13.5-alpine
    container_name: unfetter-discover-gateway
    depends_on:
     - unfetter-discover-openssl
    links:
     - unfetter-socket-server
     - unfetter-ui
     - unfetter-elk
    volumes:
     - ./config/nginx/logging.conf:/etc/nginx/conf.d.runmode/logging.conf
     - ./config/scripts/gateway-deploy-entry.sh:/gateway-deploy-entry.sh
     - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./config/nginx/uac-locations.conf:/etc/nginx/conf.d.runmode/runmode-locations.conf

     # Deploy mode is using recently on disk source code.  
     - ../unfetter-ui/dist:/etc/nginx/html
     - log-vol:/var/log
    entrypoint:
     - /gateway-deploy-entry.sh

  unfetter-discover-processor:
    build: ../unfetter-store/unfetter-discover-processor
    container_name: unfetter-discover-processor
    image: unfetter-discover-processor

  unfetter-ctf-ingest:
    build: ../unfetter-store/unfetter-ctf-ingest
    container_name: unfetter-ctf-ingest
    image: unfetter-ctf-ingest
    volumes:
     - ../unfetter-store/unfetter-ctf-ingest/test-data:/tmp/test-data
     - ../unfetter-store/unfetter-ctf-ingest/src:/usr/share/unfetter-ctf-ingest/src

  unfetter-socket-server:
    build: ../unfetter-store/unfetter-socket-server
    container_name: unfetter-socket-server
    image: unfetter-socket-server
    volumes:
      - ../unfetter-store/unfetter-socket-server/src:/usr/share/unfetter-socket-server/src
      - ./certs/:/etc/pki/tls/certs
      - ../unfetter-store/unfetter-socket-server/config/private:/usr/share/unfetter-socket-server/config/private
    environment:
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    entrypoint:
     - npm
     - start
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository

  unfetter-api-explorer:
    build: 
      context: ../unfetter-store
      dockerfile: unfetter-api-explorer/parent-context.Dockerfile
    container_name: unfetter-api-explorer
    image: unfetter-api-explorer
    volumes:
     - ../unfetter-store/unfetter-api-explorer/src:/usr/share/unfetter-api-explorer/src
     - ../unfetter-store/unfetter-discover-api/multifile-remote.yaml:/usr/share/unfetter-discover-api/multifile-remote.yaml
     - ../unfetter-store/unfetter-discover-api/api/swagger:/usr/share/unfetter-discover-api/api/swagger
    environment:
     - PUBLIC_PATH=/explorer/
    entrypoint:
     - npm
     - start

  unfetter-discover-api:
    build: ../unfetter-store/unfetter-discover-api
    container_name: unfetter-discover-api
    image: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    links:
     - unfetter-socket-server:socketserver
    volumes:
    - ./certs/:/etc/pki/tls/certs
    - ../unfetter-store/unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ../unfetter-store/unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    - ../unfetter-store/unfetter-discover-api/app.js:/usr/share/unfetter-discover-api/app.js
    - ../unfetter-store/unfetter-discover-api/config/private:/usr/share/unfetter-discover-api/config/private
    environment:
    # Options: UAC, TEST, DEMO
    - RUN_MODE=UAC
    # If deployed in a proxy, add the proxy's URL here
    entrypoint:
    - npm
    - run
    - startdeploy

  unfetter-ui:
    build: ../unfetter-ui
    image: unfetter-ui
    container_name: unfetter-ui-build
    entrypoint:
     - npm
     - run
     - build:prod:noclean
    volumes:
     - ../unfetter-ui/dist:/usr/share/unfetter-ui/dist

  unfetter-pattern-handler:
    build: ../stix2pattern
    container_name: unfetter-pattern-handler
    image: unfetter-pattern-handler
    volumes:
      - ../stix2pattern/app.py:/opt/stix/app.py
      - ../stix2pattern/test.py:/opt/stix/test.py

volumes:
  log-vol:
