version: '3.3'
services:
  unfetter-discover-gateway:
    image: nginx:1.13.5-alpine
    container_name: unfetter-discover-gateway
    volumes:
     - ./config/nginx/socket-deploy.conf:/etc/nginx/conf.d.deploy/default.conf
     - ./config/nginx/ui-dev.conf:/etc/nginx/conf.d.deploy/ui.conf

  unfetter-discover-processor:
    build: ../unfetter-store/unfetter-discover-processor
    container_name: unfetter-discover-processor
    image: unfetter-discover-processor
    volumes:
    #  TODO find a working volume mounting
     - ../unfetter-store/unfetter-discover-processor/processor.js:/usr/src/app/processor.js
  unfetter-ctf-ingest:
    build: ../unfetter-store/unfetter-ctf-ingest
    container_name: unfetter-ctf-ingest
    image: unfetter-ctf-ingest
    volumes:
     - ../unfetter-store/unfetter-ctf-ingest/test-data:/tmp/test-data
    ports:
    - "3001:10010"

  unfetter-socket-server:
    build: ../unfetter-store/unfetter-socket-server
    container_name: unfetter-socket-server
    image: unfetter-socket-server
    volumes:
      - ../unfetter-store/unfetter-socket-server/src:/usr/share/unfetter-socket-server/src
      - ./certs/:/etc/pki/tls/certs
      - ../unfetter-store/unfetter-socket-server/config/private-config.json:/usr/share/unfetter-socket-server/config/private-config.json
      - ../unfetter-store/unfetter-socket-server/config/private-config.email.json:/usr/share/unfetter-socket-server/config/private-config.email.json
    environment:
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
      # If deployed in a proxy, add the proxy's URL here
      - HTTPS_PROXY_URL=
      # Options: true, false ; NOTE Always commit set to `false`
      - SEND_EMAIL_ALERTS=false
      # This is only needed if using SEND_EMAIL_ALERTS *AND* private-config.email.json does not have a service email address
      - SERVICE_EMAIL=
    ports:
    - "13333:3333"
    entrypoint:
     - npm
     - start
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository

  cti-stix-store-repository:
    image: mongo:3.4.1
    container_name: cti-stix-store-repository
    ports:
    - "27018:27017"
    volumes:
    - ./data/db:/data/db
    # Uncomment this if using authentication
    # entrypoint: /entrypoint.sh mongod --auth


  unfetter-api-explorer:
    build: 
      context: ../unfetter-store
      dockerfile: unfetter-api-explorer/parent-context.Dockerfile
    container_name: unfetter-api-explorer
    image: unfetter-api-explorer
    volumes:
     - ../unfetter-store/unfetter-api-explorer/src:/usr/share/unfetter-api-explorer/src
     - ../unfetter-store/unfetter-discover-api/multifile-remote.yaml:/usr/share/unfetter-discover-api/multifile-remote.yaml
     - ../unfetter-store/unfetter-discover-api/api/swagger:/usr/share/unfetter-discover-api/api/swagger
    environment:
     - PUBLIC_PATH=/explorer/
    entrypoint:
     - npm
     - start

  unfetter-discover-api:
    build: ../unfetter-store/unfetter-discover-api
    container_name: unfetter-discover-api
    image: unfetter-discover-api
    depends_on:
    - unfetter-socket-server
    links:
    - unfetter-socket-server:socketserver
    ports:
    - "49360:3000"
    - "5555:5555"
    volumes:
    - ../unfetter-store/unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ../unfetter-store/unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    - ../unfetter-store/unfetter-discover-api/app.js:/usr/share/unfetter-discover-api/app.js
    - ../unfetter-store/unfetter-discover-api/config/private-config.json:/usr/share/unfetter-discover-api/config/private-config.json
    environment:
    - SOCKET_SERVER_DOMAIN = socketserver
    - SOCKET_SERVER_PORT = 3333
    - ENV=dev
    # Options: UAC, TEST, DEMO
    - RUN_MODE=UAC
    entrypoint:
    - npm
    - run
    - debugdev

  unfetter-ui:
    build: ../unfetter-ui
    image: unfetter-ui
    container_name: unfetter-ui
    volumes:
    - ../unfetter-ui/src:/usr/share/unfetter-ui/src
    - ../unfetter-ui/config:/usr/share/unfetter-ui/config
    entrypoint:
    - npm
    - run
    - serve:docker:dev:uac

  unfetter-pattern-handler:
    build: ../stix2pattern
    container_name: unfetter-pattern-handler
    image: unfetter-pattern-handler
    volumes:
      - ../stix2pattern/app.py:/opt/stix/app.py
      - ../stix2pattern/test.py:/opt/stix/test.py
    ports:
    - "5000:5000"
