version: '2'
services:
  unfetter-discover-gateway:
    image: nginx:1.13.5-alpine
    container_name: unfetter-discover-gateway
    ports:
     - "443:443"
     - "80:80"
    depends_on:
     - unfetter-discover-openssl
    links:
     - unfetter-api-explorer
     - unfetter-discover-api
     - unfetter-ctf-ingest
     - unfetter-ui
    volumes:
     - ./config/nginx/conf.d:/etc/nginx/conf.d
     - ./config/nginx/conf.d.extra/:/etc/nginx/conf.d.extra
     - ./certs/:/etc/pki/tls/certs
  unfetter-discover-openssl:
    image: svagi/openssl:latest
    container_name: unfetter-discover-openssl
    entrypoint:
     - openssl
     - req
     - -subj
     - /CN=localhost/DC=localhost/DC=localdomain
     - -new
     - -newkey
     - rsa:2048
     - -days
     - "365"
     - -nodes
     - -x509
     - -keyout
     - /tmp/certs/server.key
     - -out
     - /tmp/certs/server.crt
    volumes:
     - ./certs/:/tmp/certs

  unfetter-discover-processor:
    image: unfetter/unfetter-discover-processor:0.3.4
    container_name: unfetter-discover-processor
    volumes:
     - ./config/examples:/tmp/examples
    environment:
     - MONGO_HOST=repository
     # If deployed in a proxy, add the proxy's URL here
     - HTTPS_PROXY_URL=
    entrypoint:
     - node
     - processor.js
     - --stix
     - /tmp/examples/unfetter-stix/stix.json
     - --enhanced-stix-properties
     - /tmp/examples/unfetter-db/stix-enhancements.json
     - /tmp/examples/unfetter-db/stix-meta.json
     - --config
     - /tmp/examples/unfetter-db/config.json
     - --add-mitre-data
     - "true"
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository

  unfetter-ctf-ingest:
    container_name: unfetter-ctf-ingest
    image: unfetter/unfetter-ctf-ingest:0.3.4
    environment:
      - API_PROTOCOL=https
      - API_HOST=apihost
      - API_PORT=3000
      - API_CONTEXT=/
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    ports:
    - "3001:10010"
    entrypoint:
     - npm
     - start
    depends_on:
     - cti-stix-store-repository
     - unfetter-discover-api
    links:
     - cti-stix-store-repository:repository
     - unfetter-discover-api:apihost


  cti-stix-store-repository:
    image: mongo:3.4.1
    container_name: cti-stix-store-repository
    ports:
    - "27018:27017"
    volumes:
    - ./data/db:/data/db

  unfetter-api-explorer:
    image: unfetter/unfetter-api-explorer:0.3.4
    container_name: unfetter-api-explorer
    ports:
    - "3200:3200"
    entrypoint:
     - npm
     - start

  unfetter-discover-api:
    image: unfetter/unfetter-discover-api:0.3.4
    container_name: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository
    ports:
    - "49360:3000"
    volumes:
    - ./certs/:/etc/pki/tls/certs
    environment:
    - CTF_PARSE_HOST=http://unfetter-ctf-ingest
    - STIX_API_PROTOCOL=http
    - STIX_API_HOST=cti-stix-store
    - STIX_API_PORT=3000
    - STIX_API_PATH=cti-stix-store-api
    - MONGO_REPOSITORY=repository
    - MONGO_PORT=27017
    - MONGO_DBNAME=stix
    - ENV=dev
    # Options: UAC, TEST, DEMO
    - RUN_MODE=DEMO
    # If deployed in a proxy, add the proxy's URL here
    - HTTPS_PROXY_URL=
    entrypoint:
    - npm
    - start

  unfetter-ui:
    image: unfetter/unfetter-ui:0.3.4
    container_name: unfetter-ui
    depends_on:
    - unfetter-discover-openssl
    volumes:
    - ./certs/:/etc/pki/tls/certs
    environment:
    # Options: UAC, TEST, DEMO
    - RUN_MODE=DEMO
    entrypoint:
    - npm
    - run
    - serve:docker:dev:demo

  unfetter-pattern-handler:
    image: unfetter/unfetter-pattern-handler:0.3.4
    container_name: unfetter-pattern-handler
    ports:
    - "5000:5000"
    entrypoint:
    # ["python3","app.py","0.0.0.0"]
     - python3
     - app.py
     - 0.0.0.0
