    # To override any of the variables, just uncomment the line to override
    
    #docker_tag: "0.3.6"
    #prepath: "../../"
    #build_action: "pull" 
    #run_action: "demo"
    #use_unfetter_ui: true
    #use_uac: true
    #use_taxii: false
    #run_mode: "dev"
    #registry: "unfetter/"
    #ansible_host: "127.0.0.1"
    #ansible_ssh_private_key_file: "~/.ssh/ansible"
    #ansible_connection: "ssh"
