---


- name: "Build {{ container_name }}"
  docker_image:
    name: "{{ container_name }}"
    tag: "{{ docker_tag }}"
    state: present
    path: "{{ path }}"
  when: "build_action == 'local'"

- name: "Pull {{ container_name }}"
  docker_image:
    name: "{{ image_name }}"
    state: present
    pull: yes
  when: "build_action == 'pull'"


- name: Create Ingest
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    networks:
      - name: "{{ docker_network }}"          
    
    volumes: "{{ volume_list }} + {{ dev_volume_list if run_mode == 'dev' else '' }}"
    entrypoint:
      - npm
      - start
    env:
      API_PROTOCOL: https
      API_HOST: unfetter-discover-api
      API_PORT: 3000
      API_CONTEXT: "/"
      MONGO_REPOSITORY: repository
      MONGO_PORT: 27017
      MONGO_DBNAME: stix

    links:
     #- "unfetter-discover-api:unfetter-discover-api"
     - "cti-stix-store-repository:repository"
     
  when: run_action

