####################################################################################
#  This playbook manages the target hosts and calls "discover-tasks.yml" workhorse
#  playbook.
#  Specific target hosts can be built using the following:
#  ansible-playbook -i dev discover.yml
#
#
####################################################################################

- name: Deploy Playbook
  hosts: deployed

  tasks:
    - name: Start running the commands
      import_tasks: discover-tasks.yml
