---
####################################################################################
#  This playbook only builds the docker images locally
#
####################################################################################


- name: Prepare the Docker Host 
  hosts: deployed 
#  become: true
  vars:
     pip_install_packages:
       - name: docker
  tasks:

 # - debug:
 #     var: result

  roles:
    - { role: geerlingguy.docker, docker_users: [{{ ansible_user }}], become: true }
    - { role: geerlingguy.git, become: true }
    - { role: geerlingguy.pip, become: true }
    - unfetter  
 
